spring:
  application:
    name: shop-backend

  data:
    mongodb:
      uri: mongodb+srv://minhtrung511081_db_user:trung123@cluster0.jpxd8ef.mongodb.net/ShopTrung?retryWrites=true&w=majority&appName=Cluster0

  jwt:
    secret: 12345678901234567890123456789012345678901234567890
    expiration: 86400000